version: 2
jobs:
  build:
    working_directory: ~/emberobserver/client
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run: yarn lint:hbs
      - run: yarn lint:js
      - run: JOBS=1 COVERAGE=true yarn test
      - run: bash <(curl -s https://codecov.io/bash)
